# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Netmap < Formula
  desc "Network topology mapper with a rich terminal UI"
  homepage "https://github.com/bhancock4/netmap"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bhancock4/netmap/releases/download/v1.0.0/netmap_1.0.0_darwin_amd64.tar.gz"
      sha256 "b66ae12de887a411dd3fe5c738abe8ca86eed039fbcd5fca9d6faa48432b8290"

      define_method(:install) do
        bin.install "netmap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bhancock4/netmap/releases/download/v1.0.0/netmap_1.0.0_darwin_arm64.tar.gz"
      sha256 "f43414e4e78c5621eade889ec8b90692222113a70dc625975c0b1a3e6e4b2343"

      define_method(:install) do
        bin.install "netmap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bhancock4/netmap/releases/download/v1.0.0/netmap_1.0.0_linux_amd64.tar.gz"
      sha256 "1387ec740afc78ece8874ec6e512b7d4831b6b6513f6b95fd15ffdcedf9100b6"
      define_method(:install) do
        bin.install "netmap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bhancock4/netmap/releases/download/v1.0.0/netmap_1.0.0_linux_arm64.tar.gz"
      sha256 "9a053c248afc60cc339f812f35ba1434fb9ada4b93514d5eb89a559fcc0fc01c"
      define_method(:install) do
        bin.install "netmap"
      end
    end
  end
end
