# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Netmap < Formula
  desc "Network topology mapper with a rich terminal UI"
  homepage "https://github.com/bhancock4/netmap"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bhancock4/netmap/releases/download/v1.1.0/netmap_1.1.0_darwin_amd64.tar.gz"
      sha256 "5fc80f00b43206a6c07be2aaeb6a4a9a09c91f00b450187e8f09f1580177556f"

      define_method(:install) do
        bin.install "netmap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bhancock4/netmap/releases/download/v1.1.0/netmap_1.1.0_darwin_arm64.tar.gz"
      sha256 "4453f7f9283c1a9ec0ffd29a1232ec655c9d91131d2258a3a16cc75d62658390"

      define_method(:install) do
        bin.install "netmap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bhancock4/netmap/releases/download/v1.1.0/netmap_1.1.0_linux_amd64.tar.gz"
      sha256 "84166268b7ab1781533c1486fff558a9ff64fc30df7843e90dbc78f25e24bd7f"
      define_method(:install) do
        bin.install "netmap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bhancock4/netmap/releases/download/v1.1.0/netmap_1.1.0_linux_arm64.tar.gz"
      sha256 "7cfccc0c650a8a94c1a267a7ff9d9ac3a16fc8ed75619c721e2ef5c5c8502b6c"
      define_method(:install) do
        bin.install "netmap"
      end
    end
  end
end
